# =============================================================================
# AWS Configuration
# =============================================================================

[aws]
# S3 bucket name to use for audio files
# If commented out, the CLI will prompt you to select a bucket
s3_bucket_name = "summarizerstack-summarizerbucket670754aa-babyijstslat"

# =============================================================================
# Model Configuration
# =============================================================================

# By default, Distill CLI uses Claude 3 Sonnet from Anthropic.
# For a full list of model IDs, see https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html
# For information about inference params, see https://docs.aws.amazon.com/bedrock/latest/userguide/inference-parameters.html

[model]
model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
max_tokens = 2000
temperature = 1.0
top_p = 0.999
top_k = 40

# =============================================================================
# Prompt Configuration
# =============================================================================

[prompt]
# Prompt template for summarization
template = """
Summarize the following transcript into one or more clear and readable paragraphs. There may be multiple speakers in this transcript. If so, speakers in the transcript could be denoted by their name, or by "spk_x", where `x` is a number. These represent distinct speakers in the conversation. When you refer to a speaker, you may refer to them by "Speaker 1" in the case of "spk_1", "Speaker 2" in the case of "spk_2", and so forth. When you summarize, capture any ideas discussed, any hot topics you identify, or any other interesting parts of the conversation between the speakers. At the end of your summary, give a bullet point list of the key action items, to-do's, and followup activities. Answer in the same language as the provided transcript:
"""

# =============================================================================
# Anthropic Configuration
# =============================================================================

# Anthropic models consumed via Bedrock require additional settings
# See: https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html
# If you are not using an Anthropic model, comment out this section

[anthropic]
anthropic_version = "bedrock-2023-05-31"
system = "Your name is Distiller, and you are an AI assistant that excels at summarizing conversations."
beta = "output-128k-2025-02-19"

# =============================================================================
# Slack Integration
# =============================================================================

[slack]
# Legacy single webhook endpoint (for backward compatibility)
# webhook_endpoint = "https://hooks.slack.com/workflows/XYZ/ABC/123"

# Multiple webhook endpoints
# webhooks = [
#   { name = "General Channel", endpoint = "https://hooks.slack.com/workflows/XYZ/ABC/123" },
#   { name = "Project Team", endpoint = "https://hooks.slack.com/workflows/XYZ/DEF/456" },
#   { name = "Management", endpoint = "https://hooks.slack.com/workflows/XYZ/GHI/789" }
# ]

# =============================================================================
# Teams Integration
# =============================================================================

[teams]
# Legacy single webhook endpoint (for backward compatibility)
# webhook_endpoint = "https://prod-33.westus.logic.azure.com:443/workflows/....."

# Multiple webhook endpoints
# webhooks = [
#   { name = "General Channel", endpoint = "https://prod-33.westus.logic.azure.com:443/workflows/..." },
#   { name = "Project Team", endpoint = "https://prod-33.westus.logic.azure.com:443/workflows/..." },
#   { name = "Management", endpoint = "https://prod-33.westus.logic.azure.com:443/workflows/..." }
# ]

# Teams card icon settings
[teams.icon]
#name = "Flash"
#size = "Large"
#style = "Filled"
#color = "Accent"